package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Asientocontable generated by hbm2java
 */
@Entity
@Table(name = "asientocontable", catalog = "jazzcontadores", uniqueConstraints =
@UniqueConstraint(columnNames = {"numeroCorrelativo", "idLibroDiarioSimplificado"}))
public class AsientoContable implements java.io.Serializable {

    private Integer idAsientoContable;
    private LibroDiarioSimplificado libroDiarioSimplificado;
    private int numeroCorrelativo;
    private Date fecha;
    private String glosa;
    private List<DetalleCargo> detallesCargo = new ArrayList<DetalleCargo>();
    private List<DetalleAbono> detallesAbono = new ArrayList<DetalleAbono>();

    public AsientoContable() {
    }

    public AsientoContable(LibroDiarioSimplificado librodiariosimplificado, int numeroCorrelativo, Date fecha, String glosa) {
        this.libroDiarioSimplificado = librodiariosimplificado;
        this.numeroCorrelativo = numeroCorrelativo;
        this.fecha = fecha;
        this.glosa = glosa;
    }

    public AsientoContable(LibroDiarioSimplificado librodiariosimplificado, int numeroCorrelativo, Date fecha, String glosa, List<DetalleCargo> detallecargos, List<DetalleAbono> detalleabonos) {
        this.libroDiarioSimplificado = librodiariosimplificado;
        this.numeroCorrelativo = numeroCorrelativo;
        this.fecha = fecha;
        this.glosa = glosa;
        this.detallesCargo = detallecargos;
        this.detallesAbono = detalleabonos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idAsientoContable", unique = true, nullable = false)
    public Integer getIdAsientoContable() {
        return this.idAsientoContable;
    }

    public void setIdAsientoContable(Integer idAsientoContable) {
        this.idAsientoContable = idAsientoContable;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idLibroDiarioSimplificado", nullable = false)
    public LibroDiarioSimplificado getLibroDiarioSimplificado() {
        return this.libroDiarioSimplificado;
    }

    public void setLibroDiarioSimplificado(LibroDiarioSimplificado librodiariosimplificado) {
        this.libroDiarioSimplificado = librodiariosimplificado;
    }

    @Column(name = "numeroCorrelativo", nullable = false)
    public int getNumeroCorrelativo() {
        return this.numeroCorrelativo;
    }

    public void setNumeroCorrelativo(int numeroCorrelativo) {
        this.numeroCorrelativo = numeroCorrelativo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name = "glosa", nullable = false, length = 120)
    public String getGlosa() {
        return this.glosa;
    }

    public void setGlosa(String glosa) {
        this.glosa = glosa;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "asientoContable")
    public List<DetalleCargo> getDetallesCargo() {
        return this.detallesCargo;
    }

    public void setDetallesCargo(List<DetalleCargo> detallesCargo) {
        this.detallesCargo = detallesCargo;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "asientoContable")
    public List<DetalleAbono> getDetallesAbono() {
        return this.detallesAbono;
    }

    public void setDetallesAbono(List<DetalleAbono> detallesAbono) {
        this.detallesAbono = detallesAbono;
    }
}
