package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Comprador generated by hbm2java
 */
@Entity
@Table(name = "comprador", catalog = "jazzcontadores", uniqueConstraints =
@UniqueConstraint(columnNames = {"numeroTipoDocumentoIdentidad", "numeroDocumentoIdentidad"}))
public class Comprador implements java.io.Serializable {

    private Integer idComprador;
    private TipoDocumentoIdentidad tipoDocumentoIdentidad;
    private String razonSocialONombres;
    private String numeroDocumentoIdentidad;
    private List<ComprobanteVenta> comprobantesVenta = new ArrayList<ComprobanteVenta>();

    public Comprador() {
    }

    public Comprador(TipoDocumentoIdentidad tipodocumentoidentidad, String razonSocialOnombres, String numeroDocumentoIdentidad) {
        this.tipoDocumentoIdentidad = tipodocumentoidentidad;
        this.razonSocialONombres = razonSocialOnombres;
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    }

    public Comprador(TipoDocumentoIdentidad tipodocumentoidentidad, String razonSocialOnombres, String numeroDocumentoIdentidad, List<ComprobanteVenta> comprobanteventas) {
        this.tipoDocumentoIdentidad = tipodocumentoidentidad;
        this.razonSocialONombres = razonSocialOnombres;
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
        this.comprobantesVenta = comprobanteventas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idComprador", unique = true, nullable = false)
    public Integer getIdComprador() {
        return this.idComprador;
    }

    public void setIdComprador(Integer idComprador) {
        this.idComprador = idComprador;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "numeroTipoDocumentoIdentidad")
    public TipoDocumentoIdentidad getTipoDocumentoIdentidad() {
        return this.tipoDocumentoIdentidad;
    }

    public void setTipoDocumentoIdentidad(TipoDocumentoIdentidad tipodocumentoidentidad) {
        this.tipoDocumentoIdentidad = tipodocumentoidentidad;
    }

    @Column(name = "razonSocialONombres", nullable = false, length = 95)
    public String getRazonSocialONombres() {
        return this.razonSocialONombres;
    }

    public void setRazonSocialONombres(String razonSocialONombres) {
        this.razonSocialONombres = razonSocialONombres;
    }

    @Column(name = "numeroDocumentoIdentidad", length = 45)
    public String getNumeroDocumentoIdentidad() {
        return this.numeroDocumentoIdentidad;
    }

    public void setNumeroDocumentoIdentidad(String numeroDocumentoIdentidad) {
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comprador")
    public List<ComprobanteVenta> getComprobantesVenta() {
        return this.comprobantesVenta;
    }

    public void setComprobantesVenta(List<ComprobanteVenta> comprobanteventas) {
        this.comprobantesVenta = comprobanteventas;
    }
}
