package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Comprobantecompra generated by hbm2java
 */
@Entity
@Table(name = "comprobantecompra", catalog = "jazzcontadores", uniqueConstraints =
@UniqueConstraint(columnNames = {"numero", "serie"}))
public class ComprobanteCompra implements java.io.Serializable {

    private Integer idComprobanteCompra;
    private Proveedor proveedor;
    private TipoComprobantePagoODocumento tipoComprobantePagoODocumento;
    private String numero;
    private String serie;
    private String anioEmisionDuaOdsi;
    private Date fechaEmision;
    private Date fechaVencimientoOpago;
    private BigDecimal base;
    private BigDecimal igv;
    private BigDecimal valorAdquisicionesNoGravadas;
    private BigDecimal isc;
    private BigDecimal otrosTributosYCargos;
    private BigDecimal importeTotal;
    private CodigoAduana codigoAduana;
    private DetalleLibroRegistroCompras detalleLibroRegistroCompras;
    private DetalleLibroRegistroCompras detalleLibroRegistroComprasReferenciador;
    private List<DetalleComprobanteCompra> detallesComprobanteCompra = new ArrayList<DetalleComprobanteCompra>();

    public ComprobanteCompra() {
    }

    public ComprobanteCompra(Proveedor proveedor, TipoComprobantePagoODocumento tipocomprobantepagoodocumento, String numero, String serie, Date fechaEmision, BigDecimal base, BigDecimal igv, BigDecimal importeTotal) {
        this.proveedor = proveedor;
        this.tipoComprobantePagoODocumento = tipocomprobantepagoodocumento;
        this.numero = numero;
        this.serie = serie;
        this.fechaEmision = fechaEmision;
        this.base = base;
        this.igv = igv;
        this.importeTotal = importeTotal;
    }

    public ComprobanteCompra(Proveedor proveedor, TipoComprobantePagoODocumento tipocomprobantepagoodocumento, String numero, String serieOcodigoDep, String anioEmisionDuaOdsi, Date fechaEmision, Date fechaVencimientoOpago, BigDecimal base, BigDecimal igv, BigDecimal importeTotal) {
        this.proveedor = proveedor;
        this.tipoComprobantePagoODocumento = tipocomprobantepagoodocumento;
        this.numero = numero;
        this.serie = serieOcodigoDep;
        this.anioEmisionDuaOdsi = anioEmisionDuaOdsi;
        this.fechaEmision = fechaEmision;
        this.fechaVencimientoOpago = fechaVencimientoOpago;
        this.base = base;
        this.igv = igv;
        this.importeTotal = importeTotal;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idComprobanteCompra", unique = true, nullable = false)
    public Integer getIdComprobanteCompra() {
        return this.idComprobanteCompra;
    }

    public void setIdComprobanteCompra(Integer idComprobanteCompra) {
        this.idComprobanteCompra = idComprobanteCompra;
    }

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idProveedor", nullable = false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "numeroTipoComprobante", nullable = false)
    public TipoComprobantePagoODocumento getTipoComprobantePagoODocumento() {
        return this.tipoComprobantePagoODocumento;
    }

    public void setTipoComprobantePagoODocumento(TipoComprobantePagoODocumento tipocomprobantepagoodocumento) {
        this.tipoComprobantePagoODocumento = tipocomprobantepagoodocumento;
    }

    @Column(name = "numero", nullable = false, length = 20)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "serie", nullable = false, length = 20)
    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    @Column(name = "anioEmisionDuaODsi", length = 4)
    public String getAnioEmisionDuaOdsi() {
        return this.anioEmisionDuaOdsi;
    }

    public void setAnioEmisionDuaOdsi(String anioEmisionDuaOdsi) {
        this.anioEmisionDuaOdsi = anioEmisionDuaOdsi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaEmision", nullable = false, length = 10)
    public Date getFechaEmision() {
        return this.fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaVencimientoOPago", length = 10)
    public Date getFechaVencimientoOpago() {
        return this.fechaVencimientoOpago;
    }

    public void setFechaVencimientoOpago(Date fechaVencimientoOpago) {
        this.fechaVencimientoOpago = fechaVencimientoOpago;
    }

    @Column(name = "base", precision = 14, scale = 2)
    public BigDecimal getBase() {
        return this.base;
    }

    public void setBase(BigDecimal base) {
        this.base = base;
    }

    @Column(name = "igv", precision = 14, scale = 2)
    public BigDecimal getIgv() {
        return this.igv;
    }

    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }

    @Column(name = "importeTotal", nullable = false, precision = 14, scale = 2)
    public BigDecimal getImporteTotal() {
        return this.importeTotal;
    }

    public void setImporteTotal(BigDecimal importeTotal) {
        this.importeTotal = importeTotal;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comprobanteCompra")
    public List<DetalleComprobanteCompra> getDetallesComprobanteCompra() {
        return detallesComprobanteCompra;
    }

    public void setDetallesComprobanteCompra(List<DetalleComprobanteCompra> detallesComprobanteCompra) {
        this.detallesComprobanteCompra = detallesComprobanteCompra;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "numeroCodigoAduana")
    public CodigoAduana getCodigoAduana() {
        return codigoAduana;
    }

    public void setCodigoAduana(CodigoAduana codigoAduana) {
        this.codigoAduana = codigoAduana;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comprobanteCompra")
    public DetalleLibroRegistroCompras getDetalleLibroRegistroCompras() {
        return detalleLibroRegistroCompras;
    }

    public void setDetalleLibroRegistroCompras(DetalleLibroRegistroCompras detalleLibroRegistroCompras) {
        this.detalleLibroRegistroCompras = detalleLibroRegistroCompras;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comprobanteCompraReferenciado")
    public DetalleLibroRegistroCompras getDetalleLibroRegistroComprasReferenciador() {
        return detalleLibroRegistroComprasReferenciador;
    }

    public void setDetalleLibroRegistroComprasReferenciador(DetalleLibroRegistroCompras detalleLibroRegistroComprasReferenciador) {
        this.detalleLibroRegistroComprasReferenciador = detalleLibroRegistroComprasReferenciador;
    }

    @Column(name = "valorAdquisicionesNoGravadas", precision = 14, scale = 2)
    public BigDecimal getValorAdquisicionesNoGravadas() {
        return this.valorAdquisicionesNoGravadas;
    }

    public void setValorAdquisicionesNoGravadas(BigDecimal valorAdquisicionesNoGravadas) {
        this.valorAdquisicionesNoGravadas = valorAdquisicionesNoGravadas;
    }

    @Column(name = "isc", precision = 14, scale = 2)
    public BigDecimal getIsc() {
        return this.isc;
    }

    public void setIsc(BigDecimal isc) {
        this.isc = isc;
    }

    @Column(name = "otrosTributosYCargos", precision = 14, scale = 2)
    public BigDecimal getOtrosTributosYCargos() {
        return this.otrosTributosYCargos;
    }

    public void setOtrosTributosYCargos(BigDecimal otrosTributosYcargos) {
        this.otrosTributosYCargos = otrosTributosYcargos;
    }
}
