package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuentacontable generated by hbm2java
 */
@Entity
@Table(name = "cuentacontable", catalog = "jazzcontadores")
public class CuentaContable implements java.io.Serializable {

    private String numero;
    private CuentaContable cuentaContablePadre;
    private String denominacion;
    private ClasificacionCuenta clasificacionCuenta;
    private Set<CuentaContable> cuentasContablesHijas = new HashSet<CuentaContable>();
    private List<RegistroCuentaContable> registrosCuentaContable = new ArrayList<RegistroCuentaContable>();

    public CuentaContable() {
    }

    public CuentaContable(String numero, String denominacion, ClasificacionCuenta clasificacionCuenta) {
        this.numero = numero;
        this.denominacion = denominacion;
        this.clasificacionCuenta = clasificacionCuenta;
    }

    public CuentaContable(String numero, CuentaContable cuentacontable, String denominacion, ClasificacionCuenta clasificacionCuenta, Set<CuentaContable> cuentacontables, List<RegistroCuentaContable> registrocuentacontables) {
        this.numero = numero;
        this.cuentaContablePadre = cuentacontable;
        this.denominacion = denominacion;
        this.clasificacionCuenta = clasificacionCuenta;
        this.cuentasContablesHijas = cuentacontables;
        this.registrosCuentaContable = registrocuentacontables;
    }

    @Id
    @Column(name = "numero", unique = true, nullable = false, length = 8)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "numeroCuentaPadre")
    public CuentaContable getCuentaContablePadre() {
        return this.cuentaContablePadre;
    }

    public void setCuentaContablePadre(CuentaContable cuentaContablePadre) {
        this.cuentaContablePadre = cuentaContablePadre;
    }

    @Column(name = "denominacion", nullable = false, length = 300)
    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idClasificacionCuenta", nullable = false)    
    public ClasificacionCuenta getClasificacionCuenta() {
        return this.clasificacionCuenta;
    }

    public void setClasificacionCuenta(ClasificacionCuenta clasificacionCuenta) {
        this.clasificacionCuenta = clasificacionCuenta;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cuentaContablePadre")
    public Set<CuentaContable> getCuentasContablesHijas() {
        return this.cuentasContablesHijas;
    }

    public void setCuentasContablesHijas(Set<CuentaContable> cuentasContablesHijas) {
        this.cuentasContablesHijas = cuentasContablesHijas;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cuentaContable")
    public List<RegistroCuentaContable> getRegistrosCuentaContable() {
        return this.registrosCuentaContable;
    }

    public void setRegistrosCuentaContable(List<RegistroCuentaContable> registrosCuentaContable) {
        this.registrosCuentaContable = registrosCuentaContable;
    }
}
