package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallecargo generated by hbm2java
 */
@Entity
@Table(name = "detallecargo", catalog = "jazzcontadores")
public class DetalleCargo implements java.io.Serializable {

    private Integer idDetalleCargo;
    private RegistroCuentaContable registroCuentaContable;
    private AsientoContable asientoContable;
    private BigDecimal importe;
    private String moneda;

    public DetalleCargo() {
    }

    public DetalleCargo(RegistroCuentaContable registrocuentacontable, AsientoContable asientocontable, BigDecimal importe, String moneda) {
        this.registroCuentaContable = registrocuentacontable;
        this.asientoContable = asientocontable;
        this.importe = importe;
        this.moneda = moneda;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idDetalleCargo", unique = true, nullable = false)
    public Integer getIdDetalleCargo() {
        return this.idDetalleCargo;
    }

    public void setIdDetalleCargo(Integer idDetalleCargo) {
        this.idDetalleCargo = idDetalleCargo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idRegistroCuentaContable", nullable = false)
    public RegistroCuentaContable getRegistroCuentaContable() {
        return this.registroCuentaContable;
    }

    public void setRegistroCuentaContable(RegistroCuentaContable registrocuentacontable) {
        this.registroCuentaContable = registrocuentacontable;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idAsientoContable", nullable = false)
    public AsientoContable getAsientoContable() {
        return this.asientoContable;
    }

    public void setAsientoContable(AsientoContable asientocontable) {
        this.asientoContable = asientocontable;
    }

    @Column(name = "importe", nullable = false, precision = 14)
    public BigDecimal getImporte() {
        return this.importe;
    }

    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    @Column(name = "moneda", nullable = false, length = 20)
    public String getMoneda() {
        return this.moneda;
    }

    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
}
