package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Detallelibroregistrocompras generated by hbm2java
 */
@Entity
@Table(name = "detallelibroregistrocompras", catalog = "jazzcontadores", uniqueConstraints = {
    @UniqueConstraint(columnNames = "idComprobanteCompraReferenciado"),
    @UniqueConstraint(columnNames = "idComprobanteCompra")})
public class DetalleLibroRegistroCompras implements java.io.Serializable {

    private Integer idDetalleLibroRegistroCompras;    
    private Integer numeroCorrelativo;
    private Boolean esAdquisicionGravada;
    private String destinoAdquisicionGravada;    
    private BigDecimal tipoCambio;
    private Long numeroCompPagoSujNoDom;
    private Long numeroConstDepDetraccion;
    private Date fechaEmisionConstDepDetraccion;
    private Long numeroFinalOperDiariasSinCredFiscal;
    private Boolean marcaComprobanteSujetoAretencion;
    private String estadoOportunidadDeAnotacion;
    private Date fechaHoraRegistro;
    private LibroRegistroCompras libroRegistroCompras;
    private ComprobanteCompra comprobanteCompraReferenciado;
    private ComprobanteCompra comprobanteCompra;

    public DetalleLibroRegistroCompras() {
    }

    public DetalleLibroRegistroCompras(LibroRegistroCompras libroregistrocompras, ComprobanteCompra comprobantecompraByIdComprobanteCompra, int numeroCorrelativo) {
        this.libroRegistroCompras = libroregistrocompras;
        this.comprobanteCompra = comprobantecompraByIdComprobanteCompra;
        this.numeroCorrelativo = numeroCorrelativo;        
    }

    public DetalleLibroRegistroCompras(LibroRegistroCompras libroregistrocompras, ComprobanteCompra comprobantecompraByIdComprobanteCompraReferenciado, ComprobanteCompra comprobantecompraByIdComprobanteCompra, int numeroCorrelativo, BigDecimal tipoCambio, Long numeroCompPagoSujNoDom, Long numeroConstDepDetraccion, Date fechaEmisionConstDepDetraccion, Long numeroFinalOperDiariasSinCredFiscal, Boolean marcaComprobanteSujetoAretencion) {
        this.libroRegistroCompras = libroregistrocompras;
        this.comprobanteCompraReferenciado = comprobantecompraByIdComprobanteCompraReferenciado;
        this.comprobanteCompra = comprobantecompraByIdComprobanteCompra;
        this.numeroCorrelativo = numeroCorrelativo;        
        this.tipoCambio = tipoCambio;
        this.numeroCompPagoSujNoDom = numeroCompPagoSujNoDom;
        this.numeroConstDepDetraccion = numeroConstDepDetraccion;
        this.fechaEmisionConstDepDetraccion = fechaEmisionConstDepDetraccion;
        this.numeroFinalOperDiariasSinCredFiscal = numeroFinalOperDiariasSinCredFiscal;
        this.marcaComprobanteSujetoAretencion = marcaComprobanteSujetoAretencion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idDetalleLibroRegistroCompras", unique = true, nullable = false)
    public Integer getIdDetalleLibroRegistroCompras() {
        return this.idDetalleLibroRegistroCompras;
    }

    public void setIdDetalleLibroRegistroCompras(Integer idDetalleLibroRegistroCompras) {
        this.idDetalleLibroRegistroCompras = idDetalleLibroRegistroCompras;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idLibroRegistroCompras", nullable = false)
    public LibroRegistroCompras getLibroRegistroCompras() {
        return this.libroRegistroCompras;
    }

    public void setLibroRegistroCompras(LibroRegistroCompras libroRegistroCompras) {
        this.libroRegistroCompras = libroRegistroCompras;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idComprobanteCompraReferenciado", unique = true)
    public ComprobanteCompra getComprobanteCompraReferenciado() {
        return this.comprobanteCompraReferenciado;
    }

    public void setComprobanteCompraReferenciado(ComprobanteCompra comprobantecompraByIdComprobanteCompraReferenciado) {
        this.comprobanteCompraReferenciado = comprobantecompraByIdComprobanteCompraReferenciado;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idComprobanteCompra", unique = true, nullable = false)
    public ComprobanteCompra getComprobanteCompra() {
        return this.comprobanteCompra;
    }

    public void setComprobanteCompra(ComprobanteCompra comprobantecompraByIdComprobanteCompra) {
        this.comprobanteCompra = comprobantecompraByIdComprobanteCompra;
    }

    @Column(name = "numeroCorrelativo", nullable = false)
    public Integer getNumeroCorrelativo() {
        return this.numeroCorrelativo;
    }

    public void setNumeroCorrelativo(Integer numeroCorrelativo) {
        this.numeroCorrelativo = numeroCorrelativo;
    }

    @Column(name = "destinoAdquisicionGravada")
    public String getDestinoAdquisicionGravada() {
        return destinoAdquisicionGravada;
    }

    public void setDestinoAdquisicionGravada(String destinoAdquisicionGravada) {
        this.destinoAdquisicionGravada = destinoAdquisicionGravada;
    }

    @Column(name = "tipoCambio", precision = 4, scale = 3)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }

    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    @Column(name = "numeroCompPagoSujNoDom")
    public Long getNumeroCompPagoSujNoDom() {
        return this.numeroCompPagoSujNoDom;
    }

    public void setNumeroCompPagoSujNoDom(Long numeroCompPagoSujNoDom) {
        this.numeroCompPagoSujNoDom = numeroCompPagoSujNoDom;
    }

    @Column(name = "numeroConstDepDetraccion")
    public Long getNumeroConstDepDetraccion() {
        return this.numeroConstDepDetraccion;
    }

    public void setNumeroConstDepDetraccion(Long numeroConstDepDetraccion) {
        this.numeroConstDepDetraccion = numeroConstDepDetraccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaEmisionConstDepDetraccion", length = 10)
    public Date getFechaEmisionConstDepDetraccion() {
        return this.fechaEmisionConstDepDetraccion;
    }

    public void setFechaEmisionConstDepDetraccion(Date fechaEmisionConstDepDetraccion) {
        this.fechaEmisionConstDepDetraccion = fechaEmisionConstDepDetraccion;
    }

    @Column(name = "numeroFinalOperDiariasSinCredFiscal")
    public Long getNumeroFinalOperDiariasSinCredFiscal() {
        return this.numeroFinalOperDiariasSinCredFiscal;
    }

    public void setNumeroFinalOperDiariasSinCredFiscal(Long numeroFinalOperDiariasSinCredFiscal) {
        this.numeroFinalOperDiariasSinCredFiscal = numeroFinalOperDiariasSinCredFiscal;
    }

    @Column(name = "marcaComprobanteSujetoARetencion")
    public Boolean getMarcaComprobanteSujetoAretencion() {
        return this.marcaComprobanteSujetoAretencion;
    }

    public void setMarcaComprobanteSujetoAretencion(Boolean marcaComprobanteSujetoAretencion) {
        this.marcaComprobanteSujetoAretencion = marcaComprobanteSujetoAretencion;
    }

    @Column(name = "estadoOportunidadDeAnotacion", nullable = false, length = 1)
    public String getEstadoOportunidadDeAnotacion() {
        return this.estadoOportunidadDeAnotacion;
    }

    public void setEstadoOportunidadDeAnotacion(String estadoOportunidadDeAnotacion) {
        this.estadoOportunidadDeAnotacion = estadoOportunidadDeAnotacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechaHoraRegistro", nullable = false)
    public Date getFechaHoraRegistro() {
        return fechaHoraRegistro;
    }

    public void setFechaHoraRegistro(Date fechaHoraRegistro) {
        this.fechaHoraRegistro = fechaHoraRegistro;
    }

    @Column(name = "esAdquisicionGravada")
    public Boolean getEsAdquisicionGravada() {
        return esAdquisicionGravada;
    }
    
    public void setEsAdquisicionGravada(Boolean esAdquisicionGravada) {
        this.esAdquisicionGravada = esAdquisicionGravada;
    }

}
