package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallecomprobanteventa generated by hbm2java
 */
@Entity
@Table(name = "detallecomprobanteventa", catalog = "jazzcontadores")
public class DetalleComprobanteVenta implements java.io.Serializable {

    private Integer idDetalleComprobanteVenta;
    private ComprobanteVenta comprobanteVenta;
    private ProductoVentas productoVentas;
    private int cantidad;
    private BigDecimal precioUnitario;
    private BigDecimal subtotal;

    public DetalleComprobanteVenta() {
    }

    public DetalleComprobanteVenta(ComprobanteVenta comprobanteventa, ProductoVentas productoventas, int cantidad, BigDecimal precioUnitario, BigDecimal subtotal) {
        this.comprobanteVenta = comprobanteventa;
        this.productoVentas = productoventas;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.subtotal = subtotal;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idDetalleComprobanteVenta", unique = true, nullable = false)
    public Integer getIdDetalleComprobanteVenta() {
        return this.idDetalleComprobanteVenta;
    }

    public void setIdDetalleComprobanteVenta(Integer idDetalleComprobanteVenta) {
        this.idDetalleComprobanteVenta = idDetalleComprobanteVenta;
    }

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idComprobanteVenta", nullable = false)
    public ComprobanteVenta getComprobanteVenta() {
        return this.comprobanteVenta;
    }

    public void setComprobanteVenta(ComprobanteVenta comprobanteVenta) {
        this.comprobanteVenta = comprobanteVenta;
    }

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idProductoVentas", nullable = false)
    public ProductoVentas getProductoVentas() {
        return this.productoVentas;
    }

    public void setProductoVentas(ProductoVentas productoVentas) {
        this.productoVentas = productoVentas;
    }

    @Column(name = "cantidad", nullable = false)
    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "precioUnitario", nullable = false, precision = 14, scale = 2)
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }

    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

    @Column(name = "subtotal", nullable = false, precision = 14, scale = 2)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
}
