package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Detallelibroregistroventas generated by hbm2java
 */
@Entity
@Table(name = "detallelibroregistroventas", catalog = "jazzcontadores", uniqueConstraints = {
    @UniqueConstraint(columnNames = "idComprobanteVentaReferenciado"),
    @UniqueConstraint(columnNames = "idComprobanteVenta")})
public class DetalleLibroRegistroVentas implements java.io.Serializable {

    private Integer idDetalleLibroRegistroVentas;
    private ComprobanteVenta comprobanteVenta;
    private LibroRegistroVentas libroRegistroVentas;
    private ComprobanteVenta comprobanteVentaReferenciado;
    private int numeroCorrelativo;
    private BigDecimal valorFacturadoExportacion;
    private BigDecimal baseImponibleOpGravada;
    private BigDecimal totalOperacionExonerada;
    private BigDecimal totalOperacionInafecta;
    private BigDecimal isc;
    private BigDecimal igv_ipm;
    private BigDecimal otrosTributos;
    private BigDecimal importeTotal;
    private Long numeroFinalTicketOcintaDelDia;
    private BigDecimal tipoCambio;
    private BigDecimal baseImponibleArrozPilado;
    private BigDecimal impuestoVentasArrozPilado;
    private Byte estadoOportunidadDeAnotación;
    private Date fechaHoraRegistro;

    public DetalleLibroRegistroVentas() {
    }

    public DetalleLibroRegistroVentas(ComprobanteVenta comprobanteventaByIdComprobanteVenta, LibroRegistroVentas libroregistroventas, int numeroCorrelativo, BigDecimal importeTotal) {
        this.comprobanteVenta = comprobanteventaByIdComprobanteVenta;
        this.libroRegistroVentas = libroregistroventas;
        this.numeroCorrelativo = numeroCorrelativo;
        this.importeTotal = importeTotal;
    }

    public DetalleLibroRegistroVentas(ComprobanteVenta comprobanteventaByIdComprobanteVenta, LibroRegistroVentas libroregistroventas, ComprobanteVenta comprobanteventaByIdComprobanteVentaReferenciado, int numeroCorrelativo, BigDecimal valorFacturadoExportacion, BigDecimal baseImponibleOpGravada, BigDecimal totalOperacionExonerada, BigDecimal totalOperacionInafecta, BigDecimal isc, BigDecimal otrosTributos, BigDecimal importeTotal, Long numeroFinalTicketOcintaDelDia, BigDecimal tipoCambio, BigDecimal baseImponibleArrozPilado, BigDecimal impuestoVentasArrozPilado, Byte estadoOportunidadDeAnotación) {
        this.comprobanteVenta = comprobanteventaByIdComprobanteVenta;
        this.libroRegistroVentas = libroregistroventas;
        this.comprobanteVentaReferenciado = comprobanteventaByIdComprobanteVentaReferenciado;
        this.numeroCorrelativo = numeroCorrelativo;
        this.valorFacturadoExportacion = valorFacturadoExportacion;
        this.baseImponibleOpGravada = baseImponibleOpGravada;
        this.totalOperacionExonerada = totalOperacionExonerada;
        this.totalOperacionInafecta = totalOperacionInafecta;
        this.isc = isc;
        this.otrosTributos = otrosTributos;
        this.importeTotal = importeTotal;
        this.numeroFinalTicketOcintaDelDia = numeroFinalTicketOcintaDelDia;
        this.tipoCambio = tipoCambio;
        this.baseImponibleArrozPilado = baseImponibleArrozPilado;
        this.impuestoVentasArrozPilado = impuestoVentasArrozPilado;
        this.estadoOportunidadDeAnotación = estadoOportunidadDeAnotación;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idDetalleLibroRegistroVentas", unique = true, nullable = false)
    public Integer getIdDetalleLibroRegistroVentas() {
        return this.idDetalleLibroRegistroVentas;
    }

    public void setIdDetalleLibroRegistroVentas(Integer idDetalleLibroRegistroVentas) {
        this.idDetalleLibroRegistroVentas = idDetalleLibroRegistroVentas;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idComprobanteVenta", unique = true, nullable = false)
    public ComprobanteVenta getComprobanteVenta() {
        return this.comprobanteVenta;
    }

    public void setComprobanteVenta(ComprobanteVenta comprobanteventaByIdComprobanteVenta) {
        this.comprobanteVenta = comprobanteventaByIdComprobanteVenta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idLibroRegistroVentas", nullable = false)
    public LibroRegistroVentas getLibroRegistroVentas() {
        return this.libroRegistroVentas;
    }

    public void setLibroRegistroVentas(LibroRegistroVentas libroregistroventas) {
        this.libroRegistroVentas = libroregistroventas;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idComprobanteVentaReferenciado", unique = true)
    public ComprobanteVenta getComprobanteVentaReferenciado() {
        return this.comprobanteVentaReferenciado;
    }

    public void setComprobanteVentaReferenciado(ComprobanteVenta comprobanteventaByIdComprobanteVentaReferenciado) {
        this.comprobanteVentaReferenciado = comprobanteventaByIdComprobanteVentaReferenciado;
    }

    @Column(name = "numeroCorrelativo", nullable = false)
    public int getNumeroCorrelativo() {
        return this.numeroCorrelativo;
    }

    public void setNumeroCorrelativo(int numeroCorrelativo) {
        this.numeroCorrelativo = numeroCorrelativo;
    }

    @Column(name = "valorFacturadoExportacion", precision = 14, scale = 2)
    public BigDecimal getValorFacturadoExportacion() {
        return this.valorFacturadoExportacion;
    }

    public void setValorFacturadoExportacion(BigDecimal valorFacturadoExportacion) {
        this.valorFacturadoExportacion = valorFacturadoExportacion;
    }

    @Column(name = "baseImponibleOpGravada", precision = 14, scale = 2)
    public BigDecimal getBaseImponibleOpGravada() {
        return this.baseImponibleOpGravada;
    }

    public void setBaseImponibleOpGravada(BigDecimal baseImponibleOpGravada) {
        this.baseImponibleOpGravada = baseImponibleOpGravada;
    }

    @Column(name = "totalOperacionExonerada", precision = 14, scale = 2)
    public BigDecimal getTotalOperacionExonerada() {
        return this.totalOperacionExonerada;
    }

    public void setTotalOperacionExonerada(BigDecimal totalOperacionExonerada) {
        this.totalOperacionExonerada = totalOperacionExonerada;
    }

    @Column(name = "totalOperacionInafecta", precision = 14, scale = 2)
    public BigDecimal getTotalOperacionInafecta() {
        return this.totalOperacionInafecta;
    }

    public void setTotalOperacionInafecta(BigDecimal totalOperacionInafecta) {
        this.totalOperacionInafecta = totalOperacionInafecta;
    }

    @Column(name = "isc", precision = 14, scale = 2)
    public BigDecimal getIsc() {
        return this.isc;
    }

    public void setIsc(BigDecimal isc) {
        this.isc = isc;
    }

    @Column(name = "igv_ipm", precision = 14, scale = 2)
    public BigDecimal getIgv_ipm() {
        return igv_ipm;
    }

    public void setIgv_ipm(BigDecimal igv_ipm) {
        this.igv_ipm = igv_ipm;
    }

    @Column(name = "otrosTributos", precision = 14, scale = 2)
    public BigDecimal getOtrosTributos() {
        return this.otrosTributos;
    }

    public void setOtrosTributos(BigDecimal otrosTributos) {
        this.otrosTributos = otrosTributos;
    }

    @Column(name = "importeTotal", nullable = false, precision = 14, scale = 2)
    public BigDecimal getImporteTotal() {
        return this.importeTotal;
    }

    public void setImporteTotal(BigDecimal importeTotal) {
        this.importeTotal = importeTotal;
    }

    @Column(name = "numeroFinalTicketOCintaDelDia")
    public Long getNumeroFinalTicketOcintaDelDia() {
        return this.numeroFinalTicketOcintaDelDia;
    }

    public void setNumeroFinalTicketOcintaDelDia(Long numeroFinalTicketOcintaDelDia) {
        this.numeroFinalTicketOcintaDelDia = numeroFinalTicketOcintaDelDia;
    }

    @Column(name = "tipoCambio", precision = 4, scale = 3)
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }

    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    @Column(name = "baseImponibleArrozPilado", precision = 14, scale = 2)
    public BigDecimal getBaseImponibleArrozPilado() {
        return this.baseImponibleArrozPilado;
    }

    public void setBaseImponibleArrozPilado(BigDecimal baseImponibleArrozPilado) {
        this.baseImponibleArrozPilado = baseImponibleArrozPilado;
    }

    @Column(name = "impuestoVentasArrozPilado", precision = 14, scale = 2)
    public BigDecimal getImpuestoVentasArrozPilado() {
        return this.impuestoVentasArrozPilado;
    }

    public void setImpuestoVentasArrozPilado(BigDecimal impuestoVentasArrozPilado) {
        this.impuestoVentasArrozPilado = impuestoVentasArrozPilado;
    }

    @Column(name = "estadoOportunidadDeAnotación")
    public Byte getEstadoOportunidadDeAnotación() {
        return this.estadoOportunidadDeAnotación;
    }

    public void setEstadoOportunidadDeAnotación(Byte estadoOportunidadDeAnotación) {
        this.estadoOportunidadDeAnotación = estadoOportunidadDeAnotación;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fechaHoraRegistro", nullable = false)
    public Date getFechaHoraRegistro() {
        return fechaHoraRegistro;
    }

    public void setFechaHoraRegistro(Date fechaHoraRegistro) {
        this.fechaHoraRegistro = fechaHoraRegistro;
    }
}
