package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallecomprobantecompra generated by hbm2java
 */
@Entity
@Table(name = "detallecomprobantecompra", catalog = "jazzcontadores")
public class DetalleComprobanteCompra implements java.io.Serializable {

    private Integer idDetalleComprobanteCompra;
    private ComprobanteCompra comprobanteCompra;
    private ProductoCompras productoCompras;
    private int cantidad;
    private BigDecimal precioUnitario;
    private BigDecimal subtotal;

    public DetalleComprobanteCompra() {
    }

    public DetalleComprobanteCompra(ComprobanteCompra comprobantecompra, ProductoCompras productocompras, int cantidad, BigDecimal precioUnitario, BigDecimal subtotal) {
        this.comprobanteCompra = comprobantecompra;
        this.productoCompras = productocompras;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.subtotal = subtotal;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idDetalleComprobanteCompra", unique = true, nullable = false)
    public Integer getIdDetalleComprobanteCompra() {
        return this.idDetalleComprobanteCompra;
    }

    public void setIdDetalleComprobanteCompra(Integer idDetalleComprobanteCompra) {
        this.idDetalleComprobanteCompra = idDetalleComprobanteCompra;
    }

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idComprobanteCompra", nullable = false)
    public ComprobanteCompra getComprobanteCompra() {
        return this.comprobanteCompra;
    }

    public void setComprobanteCompra(ComprobanteCompra comprobanteCompra) {
        this.comprobanteCompra = comprobanteCompra;
    }

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "idProductoCompras", nullable = false)
    public ProductoCompras getProductoCompras() {
        return this.productoCompras;
    }

    public void setProductoCompras(ProductoCompras productoCompras) {
        this.productoCompras = productoCompras;
    }

    @Column(name = "cantidad", nullable = false)
    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "precioUnitario", nullable = false, precision = 14, scale = 2)
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }

    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }

    @Column(name = "subtotal", nullable = false, precision = 14, scale = 2)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
}
