package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Elementoplancuentas generated by hbm2java
 */
@Entity
@Table(name = "elementoplancuentas", catalog = "jazzcontadores")
public class ElementoPlanCuentas implements java.io.Serializable {

    private Byte idElementoPlanCuentas;
    private String denominacion;
    private Set<ClasificacionCuenta> clasificacionesCuentas = new HashSet<ClasificacionCuenta>();

    public ElementoPlanCuentas() {
    }

    public ElementoPlanCuentas(byte idElementoPlanCuentas, String denominacion) {
        this.idElementoPlanCuentas = idElementoPlanCuentas;
        this.denominacion = denominacion;
    }

    @Id
    @Column(name = "idElementoPlanCuentas", unique = true, nullable = false)
    public Byte getIdElementoPlanCuentas() {
        return this.idElementoPlanCuentas;
    }

    public void setIdElementoPlanCuentas(byte idElementoPlanCuentas) {
        this.idElementoPlanCuentas = idElementoPlanCuentas;
    }

    @Column(name = "denominacion", nullable = false, length = 200)
    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "elementoPlanCuentas")
    public Set<ClasificacionCuenta> getClasificacionesCuentas() {
        return clasificacionesCuentas;
    }

    public void setClasificacionesCuentas(Set<ClasificacionCuenta> clasificacionesCuentas) {
        this.clasificacionesCuentas = clasificacionesCuentas;
    }
}
