package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmpresaCliente generated by hbm2java
 */
@Entity
@Table(name = "empresacliente", catalog = "jazzcontadores", uniqueConstraints =
@UniqueConstraint(columnNames = "ruc"))
public class EmpresaCliente implements java.io.Serializable {

    private Integer idEmpresaCliente;
    private long ruc;
    private String nombreEmpresa;
    private String razonSocial;
    private String tipoRegimen;
    private String estado;
    private String descripcion;
    private String direccion;
    private String telefono1;
    private String telefono2;
    private String urlLogo;
    private Byte fechaFrontera;
    private boolean registroComprasHabilitado;
    private boolean registroVentasHabilitado;
    private boolean diarioSimplificadoHabilitado;
    private List<LibroRegistroCompras> librosRegistroCompras = new ArrayList<LibroRegistroCompras>();
    private List<LibroRegistroVentas> librosRegistroVentas = new ArrayList<LibroRegistroVentas>();    
    private List<LibroDiarioSimplificado> librosDiarioSimplificados = new ArrayList<LibroDiarioSimplificado>();
    private Contacto contacto;

    public EmpresaCliente() {
    }

    public EmpresaCliente(long ruc, String nombreEmpresa, String razonSocial, String tipoRegimen, String estado) {
        this.ruc = ruc;
        this.nombreEmpresa = nombreEmpresa;
        this.razonSocial = razonSocial;
        this.tipoRegimen = tipoRegimen;
        this.estado = estado;
    }

    public EmpresaCliente(long ruc, String nombreEmpresa, String razonSocial, String tipoRegimen, String estado, String descripcion, String direccion, String telefono1, String telefono2, String urlLogo, Byte fechaFrontera, List<LibroRegistroCompras> libroregistrocomprases, List<LibroRegistroVentas> libroregistroventases, Contacto contacto, List<LibroDiarioSimplificado> librodiariosimplificados) {
        this.ruc = ruc;
        this.nombreEmpresa = nombreEmpresa;
        this.razonSocial = razonSocial;
        this.tipoRegimen = tipoRegimen;
        this.estado = estado;
        this.descripcion = descripcion;
        this.direccion = direccion;
        this.telefono1 = telefono1;
        this.telefono2 = telefono2;
        this.urlLogo = urlLogo;
        this.fechaFrontera = fechaFrontera;
        this.librosRegistroCompras = libroregistrocomprases;
        this.librosRegistroVentas = libroregistroventases;
        this.contacto = contacto;
        this.librosDiarioSimplificados = librodiariosimplificados;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idEmpresaCliente", unique = true, nullable = false)
    public Integer getIdEmpresaCliente() {
        return this.idEmpresaCliente;
    }

    public void setIdEmpresaCliente(Integer idEmpresaCliente) {
        this.idEmpresaCliente = idEmpresaCliente;
    }

    @Column(name = "ruc", unique = true, nullable = false)
    public long getRuc() {
        return this.ruc;
    }

    public void setRuc(long ruc) {
        this.ruc = ruc;
    }

    @Column(name = "nombreEmpresa", nullable = false, length = 95)
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }

    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }

    @Column(name = "razonSocial", nullable = false, length = 95)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Column(name = "tipoRegimen", nullable = false, length = 5)
    public String getTipoRegimen() {
        return this.tipoRegimen;
    }

    public void setTipoRegimen(String tipoRegimen) {
        this.tipoRegimen = tipoRegimen;
    }

    @Column(name = "estado", nullable = false, length = 13)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "descripcion", length = 65535)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "direccion", length = 120)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "telefono1", length = 30)
    public String getTelefono1() {
        return this.telefono1;
    }

    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }

    @Column(name = "telefono2", length = 30)
    public String getTelefono2() {
        return this.telefono2;
    }

    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }

    @Column(name = "urlLogo", length = 45)
    public String getUrlLogo() {
        return this.urlLogo;
    }

    public void setUrlLogo(String urlLogo) {
        this.urlLogo = urlLogo;
    }

    @Column(name = "fechaFrontera")
    public Byte getFechaFrontera() {
        return this.fechaFrontera;
    }
    
    public void setFechaFrontera(Byte fechaFrontera) {
        this.fechaFrontera = fechaFrontera;
    }

    @Column(name = "registroComprasHabilitado", nullable = false)
    public boolean isRegistroComprasHabilitado() {
        return registroComprasHabilitado;
    }

    public void setRegistroComprasHabilitado(boolean registroComprasHabilitado) {
        this.registroComprasHabilitado = registroComprasHabilitado;
    }

    @Column(name = "registroVentasHabilitado", nullable = false)
    public boolean isRegistroVentasHabilitado() {
        return registroVentasHabilitado;
    }

    public void setRegistroVentasHabilitado(boolean registroVentasHabilitado) {
        this.registroVentasHabilitado = registroVentasHabilitado;
    }

    @Column(name = "diarioSimplificadoHabilitado", nullable = false)
    public boolean isDiarioSimplificadoHabilitado() {
        return diarioSimplificadoHabilitado;
    }

    public void setDiarioSimplificadoHabilitado(boolean diarioSimplificadoHabilitado) {
        this.diarioSimplificadoHabilitado = diarioSimplificadoHabilitado;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "empresaCliente")
    public List<LibroRegistroCompras> getLibrosRegistroCompras() {
        return this.librosRegistroCompras;
    }

    public void setLibrosRegistroCompras(List<LibroRegistroCompras> librosRegistroCompras) {
        this.librosRegistroCompras = librosRegistroCompras;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "empresaCliente")
    public List<LibroRegistroVentas> getLibrosRegistroVentas() {
        return this.librosRegistroVentas;
    }

    public void setLibrosRegistroVentas(List<LibroRegistroVentas> libroregistroventases) {
        this.librosRegistroVentas = libroregistroventases;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "empresaCliente")
    public Contacto getContacto() {
        return this.contacto;
    }

    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "empresaCliente")
    public List<LibroDiarioSimplificado> getLibrosDiarioSimplificados() {
        return this.librosDiarioSimplificados;
    }

    public void setLibrosDiarioSimplificados(List<LibroDiarioSimplificado> librodiariosimplificados) {
        this.librosDiarioSimplificados = librodiariosimplificados;
    }
}
