package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productoventas generated by hbm2java
 */
@Entity
@Table(name = "productoventas", catalog = "jazzcontadores")
public class ProductoVentas implements java.io.Serializable {

    private Integer idProductoVentas;
    private int stock;
    private String nombre;
    private BigDecimal precio;
    private String unidadDeMedida;
    private List<DetalleComprobanteVenta> detallesComprobanteVenta = new ArrayList<DetalleComprobanteVenta>();

    public ProductoVentas() {
    }

    public ProductoVentas(int stock, String nombre, BigDecimal precio) {
        this.stock = stock;
        this.nombre = nombre;
        this.precio = precio;
    }

    public ProductoVentas(int stock, String nombre, BigDecimal precio, String unidadDeMedida) {
        this.stock = stock;
        this.nombre = nombre;
        this.precio = precio;
        this.unidadDeMedida = unidadDeMedida;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idProductoVentas", unique = true, nullable = false)
    public Integer getIdProductoVentas() {
        return this.idProductoVentas;
    }

    public void setIdProductoVentas(Integer idProductoVentas) {
        this.idProductoVentas = idProductoVentas;
    }

    @Column(name = "stock")
    public int getStock() {
        return this.stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "precio", precision = 14, scale = 2)
    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @Column(name = "unidadDeMedida", length = 45)
    public String getUnidadDeMedida() {
        return this.unidadDeMedida;
    }

    public void setUnidadDeMedida(String unidadDeMedida) {
        this.unidadDeMedida = unidadDeMedida;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "productoVentas")
    public List<DetalleComprobanteVenta> getDetallesComprobanteVenta() {
        return detallesComprobanteVenta;
    }

    public void setDetallesComprobanteVenta(List<DetalleComprobanteVenta> detallesComprobanteVenta) {
        this.detallesComprobanteVenta = detallesComprobanteVenta;
    }
}
