package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "jazzcontadores", uniqueConstraints =
@UniqueConstraint(columnNames = {"numeroTipoDocumentoIdentidad", "numeroDocumentoIdentidad"}))
public class Proveedor implements java.io.Serializable {

    private Integer idProveedor;
    private TipoDocumentoIdentidad tipoDocumentoIdentidad;
    private String razonSocial;
    private String numeroDocumentoIdentidad;
    private List<ComprobanteCompra> comprobantesCompra = new ArrayList<ComprobanteCompra>();

    public Proveedor() {
    }

    public Proveedor(String razonSocial, String numeroDocumentoIdentidad) {
        this.razonSocial = razonSocial;
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    }

    public Proveedor(TipoDocumentoIdentidad tipodocumentoidentidad, String razonSocial, String numeroDocumentoIdentidad) {
        this.tipoDocumentoIdentidad = tipodocumentoidentidad;
        this.razonSocial = razonSocial;
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idProveedor", unique = true, nullable = false)
    public Integer getIdProveedor() {
        return this.idProveedor;
    }

    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "numeroTipoDocumentoIdentidad")
    public TipoDocumentoIdentidad getTipoDocumentoIdentidad() {
        return this.tipoDocumentoIdentidad;
    }

    public void setTipoDocumentoIdentidad(TipoDocumentoIdentidad tipodocumentoidentidad) {
        this.tipoDocumentoIdentidad = tipodocumentoidentidad;
    }

    @Column(name = "razonSocial", nullable = false, length = 60)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Column(name = "numeroDocumentoIdentidad", nullable = false, length = 15)
    public String getNumeroDocumentoIdentidad() {
        return this.numeroDocumentoIdentidad;
    }

    public void setNumeroDocumentoIdentidad(String numeroDocumentoIdentidad) {
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "proveedor")
    public List<ComprobanteCompra> getComprobantesCompra() {
        return comprobantesCompra;
    }

    public void setComprobantesCompra(List<ComprobanteCompra> comprobantesCompra) {
        this.comprobantesCompra = comprobantesCompra;
    }
}
