package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipodocumentoidentidad generated by hbm2java
 */
@Entity
@Table(name = "tipodocumentoidentidad", catalog = "jazzcontadores")
public class TipoDocumentoIdentidad implements java.io.Serializable {

    private String numero;
    private String descripcion;

    public TipoDocumentoIdentidad() {
    }

    public TipoDocumentoIdentidad(String numero, String descripcion) {
        this.numero = numero;
        this.descripcion = descripcion;
    }

    @Id
    @Column(name = "numero", unique = true, nullable = false, length = 1)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
