package com.jazzcontadores.model.entities;
// Generated 07/04/2013 11:07:12 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipocomprobantepagoodocumento generated by hbm2java
 */
@Entity
@Table(name = "tipocomprobantepagoodocumento", catalog = "jazzcontadores")
public class TipoComprobantePagoODocumento implements java.io.Serializable {

    private Byte numero;
    private String descripcion;

    public TipoComprobantePagoODocumento() {
    }

    public TipoComprobantePagoODocumento(byte numero, String descripcion) {
        this.numero = numero;
        this.descripcion = descripcion;
    }

    @Id
    @Column(name = "numero", unique = true, nullable = false)
    public Byte getNumero() {
        return this.numero;
    }

    public void setNumero(Byte numero) {
        this.numero = numero;
    }

    @Column(name = "descripcion", nullable = false, length = 400)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
